### PR TITLE
Extending init.js to support separate configuration files

### PR DESCRIPTION
**Pull request by nemisj**
Added:
- Possibility to run on remote selenium-hub ( galen.hub.json as example )
- Added `.only` postfix to `testOnAllDevices` and `testOnDevice` functions
- Added Warning if requested device in `testOnDevice` is not found in configuration
- App-wide configuration support using getConfig() function

### CODE REVIEW

**Comment by ishubin** [comment]
The JSON configuration looks nice, but what if I want to add another device? Normally I would just put that  into ```devices``` variable. But now it seems like you have it repeated in init.js ```allowedDevices ``` variable and in the config. But what if my device is too specific like (e.g. if its called iPhone)
 
Other then that I like your solution but I am afraid it might not work for me. Lately I've been working on some code to support tests execution in SauceLabs, local physical devices with Appium and local desktop browser. With your config and js setup I am not sure if it will be easy to achieve that. Let me explain my vision: in some cases I might choose to run all tests on SauceLabs cloud, and in some cases I would choose to run them locally on my android phones connected to my laptop. In the end I decided to change the purpose of ```devices``` variable. What I did (and I haven't pushed yet unfortunately) is I made each devices responsible of giving a WebDriver instance to a test. So instead of creating a driver in tests I expect that each devices has ```openDriver``` function. This allows me to mix any kind of setups in my tests. Here is an example of SauceLabs setup:

```
function inSauceLabs(deviceName, tags, gridSettings) {
    return {
        deviceName: deviceName,
        tags: tags,
        openDriver: function () {
            return createGridDriver(SAUCELABS_GRID_URL, gridSettings);
        }
    }
}

var devices = {
    htcOneX: inSauceLabs("HTC One X", ["mobile"], {
        browser: "android",
        desiredCapabilities: {
            platform: "Linux",
            version: "4.1",
            deviceName: "HTC One X Emulator",
            deviceOrientation: "portrait"
        }
    }),
    googleNexus7C: inSauceLabs("Google Nexus 7C", ["tablet"], {
        browser: "android",
        desiredCapabilities: {
            platform: "Linux",
            version: "4.1",
            deviceName: "Google Nexus 7C Emulator",
            deviceOrientation: "portrait"
        }
    }),
    Windows_10_IE11: inSauceLabs("Internet Explorer 11", ["desktop"], {
        browser: "internet explorer",
        desiredCapabilities: {
            platform: "Windows 10",
            version: "11.0"
        }
    }),
    iPhone_iOS_6: inSauceLabs("iPhone iOS 6.0", ["mobile"], {
        browser: "iphone",
        desiredCapabilities: {
            platform: "OS X 10.10",
            version: "6.0",
            deviceName: "iPhone Simulator",
            deviceOrientation: "portrait"
        }
    }),
    iPad_6: inSauceLabs("iPad IOS 6.0", ["tablet"], {
        browser: "iphone",
        desiredCapabilities: {
            platform: "OS X 10.10",
            version: "6.0",
            deviceName: "iPad Simulator",
            deviceOrientation: "portrait"
        }
    }),
    iPhone_iOS_8: inSauceLabs("iPhone iOS 8.0", ["mobile"], {
        browser: "iphone",
        desiredCapabilities: {
            platform: "OS X 10.10",
            version: "8.0",
            deviceName: "iPhone Simulator",
            deviceOrientation: "portrait"
        }
    })
};
```

And now this is how I get a WebDriver instance in the test:

```
function openDriver(device, url) {
    var driver = device.openDriver();

    session.put("driver", driver);

    if (url != null) {
        if (url.indexOf("http://") != 0 && url.indexOf("https://") != 0) {
            url = "http://" + domain + url;
        }
        driver.get(url);
    }
    else {
        driver.get("http://" + domain);
    }
    return driver;
}
```

Then I can do the same for local Appium based tests. I could write a function like ```onDesktopDriver``` and ```onAppiumDriver``` and then use both of them in my devices variable. By the way here is an example of doing such thing https://www.youtube.com/watch?v=zmbqTe0aUtc

I wanted to introduce such solution a long time ago but just keep on forgetting constantly :)
What is your opinion on this?

**Comment by ishubin** [comment]
So in short what my vision on this ```init.js``` - I was planing to extend it to support multiple selenium grids and local webdrivers within one run. So that you could configure you own grid and run your tests in it together with SauceLabs or BrowserStack grid. That would be nice if you want save some money :)

**Comment by nemisj** [comment]
I will do it in a quotes way not to loose the idea what i want to say :)

> The JSON configuration looks nice, but what if I want to add another device? Normally I would just put that into devices variable. But now it seems like you have it repeated in init.js allowedDevices variable and in the config. But what if my device is too specific (e.g. if its called "iPhone on iOS 9.0")

Maybe this configuration is a bit 'strict', but what it gives you is a standardized way of 'calling' things. We have 3 'abstract' devices: 'desktop', 'mobile', 'tablet' and that's it. whether it's a iPhone or Android device doesn't matter. It's a 'mobile' and I thought galen is responsive framework and it should work on 'mobile' devices the same, no matter  whether this is android or iPhone device.

I will explain why is this so important. In init.js we have function "testOnDevice". If we would have all the different devices called by name "iphone", "android" you would start using it also in testOnDevice function, like

```javascript
testOnDevice(devices.iPhone)
````

and in another test would you do

```javascript
testOnDevice(devices.android
```

In this way, actually the name in configuration pushes the way you call it in your test. This means, that you want' be able to have the same tests for different devices.

As you said, i want to run it loccaly, on remote appium machine, on browser stack and it should be the same, no differentiations for the tests.

For example for now, I have 3 config files:

galen.local.json
galen.browserstack.json
galen.hub.json

All of them use different devices, but use the same name, in this way, I ensure that actually my tests are unified across all the devices. Even if one of the devices is not in the list, inside init.js I can track this and give a warning.

Look for example at the galen.browserstack.json

```javascript
{
	"domain" : "test.galenframework.com",
	"gridUrl": "hub.browserstack.com:80/wd/hub",
	"devices": {

		"mobile": {
			"deviceName": "mobile",
			"browser": "iphone",
			"desiredCapabilities": {
				"browserName" : "iPhone",
				"platform" : "MAC",
				"device" : "iPhone 5S",
				"emulator" : "true"
			}
		},

		"tablet": {
			"deviceName": "ipad",
			"browser": "ipad",
			"desiredCapabilities": {
				"browserName" : "iPad",
				"platform" : "MAC",
				"device" : "iPad Air",
				"emulator" : "true"
			}
		},

		"desktop" : {
			"deviceName": "desktop",
			"browser": "chrome",
			"size": "1280x800",
			"desiredCapabilities": {
				"browser" : "Chrome",
				"browser_version" : "44.0",
				"os" : "Windows",
				"os_version" : "8.1",
				"resolution" : "1280x800"
			}
		}
	}
}
```

and the hub config you've seen in pull request. 

So now, I run the same tests on different devices just with very generic names 'tablet', 'mobile', 'desktop' and if it breaks somewhere, it means that my UI interface is not really browser/device independent. And this is actually what is my aim of the galen tests, I really want to ensure that tested app/website is device independent. No matter whether this is Android or iPhone or just a browser in a browser which is resized.

Don't think that i'm attacking your idea, or your solution, but in my opinion such differentiation on a test level creates extra 'custom' code, which I personally would like to avoid.

Btw, looking at your current solution, i'm thinking that I could use the 'tags' keyword actually to verify the devices against `allowedDevices` list. In that way, it would also work for your proposed solutions, because then you could specify different devices and having different configurations for every grid system.

**Comment by nemisj** [comment]
>So in short what my vision on this init.js - I was planing to extend it to support multiple selenium grids and local webdrivers within one run. So that you could configure you own grid and run your tests in it together with SauceLabs or BrowserStack grid. That would be nice if you want save some money :)

I see what you mean. I was thinking from the single run - single grid instance, that's why it's implemented this way. I will close the PR then :)

**Comment by ishubin** [comment]
Exactly, I completely agree with what you said above. I also think that tests should not depend on a specific device. But what I meant is that I want to run something like this: 3 mobile (ios, samsung, htc), 4 desktop (firefox, chrome, ie, safari) and 4 tablets (ipad, asus, samsung etc) in a single run. So, yeah, validating the tags would make more sense in this case.

Let me first push what I was planning to do and then we can come back to this disucssion. Maybe we can merge the two ideas later.

P. S. In then end I don't want to limit users. If you choose to run your tests in different processes, then I think it is also an important option. At the same time I would like to be able to run everything within one go.

**Comment by nemisj** [comment]
Good idea, will wait for your push :)

**Comment by ishubin** [comment]
Here is what I have added https://github.com/galenframework/galen-sample-tests/commit/a77aeb6529931ac7a13f3ac77f364fddd1ed8a59

Don't have time to make it prettier.

**Pull request closed without merging**
